### ISSUE TITLE
Constant Tidar token refreshing

### ISSUE THREAD

**Issue by d3mystified** [cstaelen/tidarr#359]
I'm on the latest stable (and also the testing) and see the Tidal token being refreshed constantly:

```
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
Refreshing Tidal token...
Tidal token refreshed.
```

Is this expected?

**Comment by cstaelen** [comment]
Thank for reporting the bug 🙏 
Is it fixed in `cstaelen/tidarr:testing` ?

**Comment by d3mystified** [comment]
Still happening on image with `sha256:b679b24770fa5d98ffc5b0d688c1f9473d8095248c3a464bd9d52e3a3194c932`.

**Comment by cstaelen** [comment]
Should be fixed in last release (0.3.5)
If the issue persists, please give more details about when does it happened, and particular user action.

Thanks

**Comment by cstaelen** [comment]
I close the issue to clean the board.
Feel free to reopen it if you think it's relevant 👍

**Comment by diegocade1** [comment]
Hey there, this is still happening

<img width="404" height="430" alt="Image" src="https://github.com/user-attachments/assets/2b1f3683-7e5c-4baa-99cd-cbc3296ea705" />

I have the latest version 0.3.5

<img width="527" height="349" alt="Image" src="https://github.com/user-attachments/assets/d2d15c38-8d8c-4006-9033-c55fe797a4b1" />

Cant use the app at the moment.

**Comment by wwwb0n3zcom** [comment]
I'm getting the same thing. I was running 0.3.4 and then upgraded to 0.3.5 once notified in the app. I was working fine for days until today.

I have tried to rebuild even going back to 0.3.4 after removing the configurations. Same issue occurs "No Tidal token found !". So the main page just keeps refreshing non-stop.

Looking at my logs (now with a clean build of 0.3.5) - I have the same over and over:

```
2025-10-16 01:51:55 Refreshing Tidal token...
2025-10-16 01:51:56 Tidal token refreshed.
2025-10-16 01:51:57 Python script exited with code 1
2025-10-16 01:51:57 Refreshing Tidal token...
2025-10-16 01:51:58 Tidal token refreshed.
2025-10-16 01:51:59 Python script exited with code 1
```

Tried using the following within the docker container:
```
tiddl auth login
```

<img width="668" height="547" alt="Image" src="https://github.com/user-attachments/assets/3dec7bba-6386-41b4-9cca-e56aee9d1e23" />

**Comment by cstaelen** [comment]
Hi, 
It should be fixed on testing image : `cstaelen/tidarr:testing`.
It will be the next release.

Could you please tell if the bug is fixed on your side ?
It should released soon.

**Comment by SkylerGhostly** [comment]
> Hi, It should be fixed on testing image : `cstaelen/tidarr:testing`. It will be the next release.
> 
> Could you please tell if the bug is fixed on your side ? It should released soon.

Still having this problem while on testing tag. 

Here's my attempt at trying to re-auth:
```
root@817a55ba6791:/home/app/standalone# tiddl auth login
[22:30:43] INFO     Already logged in.                                                        auth.py:53
           INFO     Refreshing token...                                                       auth.py:35
Traceback (most recent call last):
  File "/root/.venvs/bin/tiddl", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/root/.venvs/lib/python3.12/site-packages/click/core.py", line 1462, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venvs/lib/python3.12/site-packages/click/core.py", line 1383, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/.venvs/lib/python3.12/site-packages/click/core.py", line 1850, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venvs/lib/python3.12/site-packages/click/core.py", line 1850, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venvs/lib/python3.12/site-packages/click/core.py", line 1246, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venvs/lib/python3.12/site-packages/click/core.py", line 814, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venvs/lib/python3.12/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venvs/lib/python3.12/site-packages/tiddl/cli/ctx.py", line 57, in wrapper
    return func(custom_ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venvs/lib/python3.12/site-packages/tiddl/cli/auth.py", line 54, in login
    ctx.invoke(refresh)
  File "/root/.venvs/lib/python3.12/site-packages/click/core.py", line 814, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venvs/lib/python3.12/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venvs/lib/python3.12/site-packages/tiddl/cli/ctx.py", line 57, in wrapper
    return func(custom_ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venvs/lib/python3.12/site-packages/tiddl/cli/auth.py", line 36, in refresh
    token = refreshToken(auth.refresh_token)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venvs/lib/python3.12/site-packages/tiddl/auth.py", line 91, in refreshToken
    raise AuthError(**data)
tiddl.exceptions.AuthError: 401: invalid_client - Client id 3235 not found
```

Edit: 
Image Digest: `sha256:f890ee9cbfd693f08bec2a9c9c54bccad28c7153d66cff8f6c22aab1c2aa630b`

Edit 2:
Following the instructions [here](https://github.com/cstaelen/tidarr/issues/382#issuecomment-3410823839) has fixed the issue for me.
