### ISSUE TITLE
Chown error causing container to shutdown.  "cannot access '/home/app/standalone/download/incomplete/*'"

### ISSUE THREAD

**Issue by ChuckMCCluck** [cstaelen/tidarr#438]
🕖 [TIDDL] Executing: TIDDL_PATH=/home/app/standalone/shared tiddl fav -r album download -q master

node:internal/errors:983
  const err = new Error(message);
              ^

Error: Command failed: chown -R 99:100 /home/app/standalone/download/incomplete/*
chown: cannot access '/home/app/standalone/download/incomplete/*': No such file or directory

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:882:11)
    at execSync (node:child_process:954:15)
    at setPermissions (/home/app/standalone/api/dist/src/helpers/jobs.js:101:59)
    at postProcessing (/home/app/standalone/api/dist/src/helpers/ProcessingStack.js:222:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  status: 1,
  signal: null,
  output: [
    null,
    '',
    "chown: cannot access '/home/app/standalone/download/incomplete/*': No such file or directory\n"
  ],
  pid: 90,
  stdout: '',
  stderr: "chown: cannot access '/home/app/standalone/download/incomplete/*': No such file or directory\n"
}

Node.js v22.15.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**My container settings for Tidarr are as follows (I have the container setup through Unraid using environment variables):**

ENABLE_BEETS:true
SYNC_CRON_EXPRESSION:*/30 * * * *
ENABLE_PLEX_UPDATE:true
PLEX_URL:http://192.168.8.146:32400
PLEX_LIBRARY:3
PLEX_TOKEN:CENSORED
PUID:99
PGID:100
UMASK:000

**Beets config file settings:** 

plugins: embedart importadded
art_filename: folder
threaded: yes
per_disc_numbering: yes
id3v23: no
asciify_paths: true

ui:
    color: no

paths:
    default: %asciify{$albumartist}/$original_year - %asciify{$album}%aunique{}/$track - %asciify{$title}
    singleton: Non-Album/%asciify{$artist} - %asciify{$title}
    comp: Compilations/%asciify{$album}%aunique{}/$track - %asciify{$title}
    albumtype_soundtrack: Soundtracks/%asciify{$album}%aunique{}/$track - %asciify{$title}

import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: no
    quiet_fallback: skip
    timid: no
    duplicate_action: skip
    log: /home/app/standalone/shared/beets/beet.log
    languages: ['en']
    group_albums: no

match:
    strong_rec_thresh: 0.10 # 0.04
    medium_rec_thresh: 0.25 # 0.25
    rec_gap_thresh: 0.25 # 0.25
    max_rec:
        missing_tracks: medium # medium
        unmatched_tracks: medium # medium
        track_length: medium
        track_index: medium
    distance_weights:
        source: 2.0 # 2.0
        artist: 3.0 # 3.0
        album: 3.0 # 3.0
        media: 1.0 # 1.0
        mediums: 1.0 # 1.0
        year: 1.0 # 1.0
        country: 0.5 # 0.5
        label: 0.5 # 0.5
        catalognum: 0.5 # 0.5
        albumdisambig: 0.5 # 0.5
       album_id: 5.0 # 5.0
        tracks: 2.0 # 2.0
        missing_tracks: 0.9 # 0.9
        unmatched_tracks: 0.6 # 0.6
        track_title: 3.0 # 3.0
        track_artist: 2.0 # 2.0
        track_index: 1.0 # 1.0
        track_length: 2.0 # 2.0
        track_id: 5.0 # 5.0
    preferred:
        countries: [] # []
        media: [] # []
        original_year: no # no
    ignored: ['missing_tracks', 'track_length', 'unmatched_tracks', 'track_index'] # []
    required: [] # []
    ignored_media: [] # []
    ignore_data_tracks: yes # yes
    ignore_video_tracks: yes # yes
    track_length_grace: 10 # 10
    track_length_max: 30 # 30

embedart:
    auto: no

importadded:
    preserve_mtimes: yes
    preserve_write_mtimes: yes

permissions:
    file: 644
    dir: 755

**Everything seems to work fine when downloading anything manually and the initial first run of the watchlist but this error seems to rear its head whenever the container executes the watchlist cron job, at least that from what I've gathered but I could be wrong.**

**Comment by cstaelen** [comment]
The error prompt when incomplete folder is empty. 
What sound like there is no new fav album in you list since last watch.

I should handle this case 👍

**Comment by cstaelen** [comment]
@ChuckMCCluck I pushed a fix on `cstaelen/tidarr:testing` 
Could you please tell me if that fix the issue on your setup ?

**Comment by ChuckMCCluck** [comment]
> [@ChuckMCCluck](https://github.com/ChuckMCCluck) I pushed a fix on `cstaelen/tidarr:testing` Could you please tell me if that fix the issue on your setup ?

It seems to have fixed the issue of the container crashing and shutting off, thank you. Tidarr still throws the same error but the container doesn't shutdown anymore.

**Comment by cstaelen** [comment]
The fix is now available in the last Tidarr release (1.0.0)
I close this issue but feel free to open a new one if relevant 👍
