### ISSUE TITLE
New player doesn't play nothing

### ISSUE THREAD

**Issue by esturniolo** [cstaelen/tidarr#539]
Hello!

I'm trying to use the new player but never plays anything.

<img width="394" height="202" alt="Image" src="https://github.com/user-attachments/assets/43c6ce35-1196-48be-ad14-9c459d034569" />

<img width="381" height="186" alt="Image" src="https://github.com/user-attachments/assets/8b8f79e9-a3ca-419e-829e-a810bc27f7ff" />

<img width="381" height="196" alt="Image" src="https://github.com/user-attachments/assets/08d34ace-0a49-42f1-b3a8-4f8ea0287093" />

Everytime that I press the play button into a song, the Pop up appears, the image of the wavesounds starts to move but the audio never starts and the time is always in 0.
I added several different styles on the captures just in case.

I'm doing something wrong? Should I configure something?
Shoudl I add something in my compose, some bind path for those temp files?

Thanks!!!

**Comment by cstaelen** [comment]
Thanks for reporting 👍 

Could you please provide any browser/console logs ?
There is nothing more to do normally

**Comment by esturniolo** [comment]
sure!

I've this con the browser console

````
/album/1212315:1 Mixed Content: The page at 'https://tidarr.my.instance/album/1212315' was loaded over HTTPS, but requested an insecure element 'http://10.1.10.142:8484/api/stream/play/1212316?exp=1765210276&sig=d023974580fee538a0bd051157dc19aec5922bad1a3817fd2f0aca5805fe08d5'. This request was not upgraded to HTTPS because its URL's host is an IP address.
/album/1212315:1 Mixed Content: The page at 'https://tidarr.my.instance/album/1212315' was loaded over HTTPS, but requested an insecure audio file 'http://10.1.10.142:8484/api/stream/play/1212316?exp=1765210276&sig=d023974580fee538a0bd051157dc19aec5922bad1a3817fd2f0aca5805fe08d5'. This request has been blocked; the content must be served over HTTPS.
index-_eO-rn_P.js:441 Autoplay blocked: NotSupportedError: Failed to load because no supported source was found.
(anonymous) @ index-_eO-rn_P.js:441
Promise.catch
(anonymous) @ index-_eO-rn_P.js:441
ac @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
ba @ index-_eO-rn_P.js:8
j1 @ index-_eO-rn_P.js:8
Q1 @ index-_eO-rn_P.js:8
Af @ index-_eO-rn_P.js:8
ex @ index-_eO-rn_P.js:8
fc @ index-_eO-rn_P.js:8
X1 @ index-_eO-rn_P.js:8
F1 @ index-_eO-rn_P.js:8
P1 @ index-_eO-rn_P.js:8
z1 @ index-_eO-rn_P.js:8
q1 @ index-_eO-rn_P.js:8
H @ index-_eO-rn_P.js:1
````

Now that I'm looking this log, it seems that the audio comes from a HTTP and as I'm serving the web on a HTTPS web using a reverse proxy, that generates the classic "mixed content"

**Comment by cstaelen** [comment]
Thanks for providing logs 👍 
Indeed you are right, the classic CORS issue :) 
That make sense as your instance is public. 
A fix is coming !

**Comment by cstaelen** [comment]
I deployed the feature on `cstaelen/tidarr:testing`.
Could you please confirm that the issue is fixed ?

Thank you

**Comment by esturniolo** [comment]
> I deployed the feature on `cstaelen/tidarr:testing`. Could you please confirm that the issue is fixed ?
> 
> Thank you

Sadly is not fixed yet.

````
1212315:1 Mixed Content: The page at 'https://tidarr.my.instance/album/1212315' was loaded over HTTPS, but requested an insecure element 'http://10.1.10.142:8484/api/stream/play/1212316?exp=1765283040&sig=46191b75a51b5ed5c38bfc3d2b560d734947eccfd5a13aac5cd46b72a649c200'. This request was not upgraded to HTTPS because its URL's host is an IP address.
1212315:1 Mixed Content: The page at 'https://tidarr.my.instance/album/1212315' was loaded over HTTPS, but requested an insecure audio file 'http://10.1.10.142:8484/api/stream/play/1212316?exp=1765283040&sig=46191b75a51b5ed5c38bfc3d2b560d734947eccfd5a13aac5cd46b72a649c200'. This request has been blocked; the content must be served over HTTPS.
````

````
$ docker image ls | grep "cstaelen/tidarr"
cstaelen/tidarr                       testing                              5effc5c3dd93   12 hours ago    477MB
cstaelen/tidarr                       latest                               76e679eb8359   3 days ago      468MB
cstaelen/tidarr                       <none>                               b4f4ce8371a6   5 weeks ago     358MB

$ docker ps -a | grep tidarr
a063f74fa74f   cstaelen/tidarr:testing                          "/init"                  21 minutes ago   Up 21 minutes (healthy)   0.0.0.0:8484->8484/tcp, [::]:8484->8484/tcp                                                    tidarr
````

And my instance isn't public. Runs locally and only in my network 😀

**Comment by cstaelen** [comment]
Indeed i misread the urls, I just saw "https" + domain -> public 😁
This time player should be ok over https (tidarr:testing) 🤞

**Comment by esturniolo** [comment]
And we've a winner!!!!

Now it's working like a charm!!

Thanks a lot for you effort!
